org: franpanozzo
app: periodic-exc-api
service: periodic-exc-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  stage: prod
  timeout: 100
  region: us-east-1

functions:
  handler:
    handler: handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      PORT: 8000

plugins:
  - serverless-offline